datarockets/ruby-style

default.yml

Fixed issue https://github.com/datarockets/datarockets-style/issues/11

Remove rubocop-rails_config dependency from config which we're not setting up

---

CONTRIBUTING.md
README.md

Used rubocop contributing notes as base https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md

[Fix #4] Add Contributing notes

---

STYLE_GUIDE.md

Close #24 
This PR adds a table of contents and links to style guide doc
Before
Now

[Fix #24] Change style guide format

---

CHANGELOG.md
STYLE_GUIDE.md
default.yml

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyMethod
https://github.com/datarockets/datarockets-style/issues/56

[#56] Write empty methods in expanded way

---

CHANGELOG.md
default.yml

See https://github.com/datarockets/datarockets-style/issues/57

[Fix #57] Disable Lint/AmbiguousBlockAssociation with Rspec syntax

---

CHANGELOG.md
STYLE_GUIDE.md
default.yml

This PR temporary resolve issue #32 (so it does not have `Fix` label). see https://github.com/datarockets/datarockets-style/issues/32#issuecomment-514613328
So this PR just disable this cop for now. 

[#32] Disable magic comment cop

---

CHANGELOG.md
STYLE_GUIDE.md
config/default.yml

https://github.com/datarockets/datarockets-style/issues/73
https://rubocop.readthedocs.io/en/latest/cops_style/#stylebracesaroundhashparameters

Add style for curly braces around hash params

---

CHANGELOG.md
STYLE_GUIDE.md
config/default.yml

Change style for `RSpec/ExpectChange` cop to `block`. 

[Fix #96] Setup RSpec/ExpectChange cop

---

Gemfile.lock
datarockets-style.gemspec

I remove `bundler` as a local dependency cause usually we install it into the home directory. @dzhlobo @AleksSenkou  How do you think:  is it a good idea?

Remove bundler as local dependency

---

CHANGELOG.md
Gemfile.lock
datarockets-style.gemspec

Release Notes: https://github.com/rubocop-hq/rubocop/releases/tag/v0.76.0

[Fix #113] Update RuboCop version to 0.76.0

---

.rubocop.yml
CHANGELOG.md
config/base.yml

The problem is that when we add exclude in rubocop.yml file it overrides exclude inherited from config/ruby.yml and config/rspec.yml.
Found how not to override Excludes but extend - `inherit_mode`
1. Create file with style mistake. Run rubocop and see offense.
2. Add this code to rubocop.yml in order to exclude our file with mistake:
`# .rubocop.yml`
```
AllCops:
TargetRubyVersion: 2.3
Exclude:
- "test.rb"
```
Run rubocop again and see that our new file excluded because we don't see offense in it anymore. **But** we see offense in other file. 
Our Exclude has overridden current Exclude. That's why we got offense in file - it is not Excluded anymore.
3. Add this code in …

[Fix #80] Added inherit_mode in .rubocop.yml in order to extend Excludes not override

---

CHANGELOG.md
config/base.yml
doc/STYLE_GUIDE.md
lib/datarockets/style.rb
lib/datarockets/style/cop/layout/array_alignment_extended.rb
spec/datarockets/style/cop/layout/array_alignment_extended_spec.rb
spec/spec_helper.rb

We want to write arrays this way:
```ruby
method_object %i[steps_data! start_step! checks_data! actions_data! waits_data! notes_data!
connections_data! timezone! workflow!]
```
But rubocop doesn't support this style. It forces to write this way:
```ruby
method_object %i[steps_data! start_step! checks_data! actions_data! waits_data! notes_data!
connections_data! timezone! workflow!]
```
We could only disable this rule.
How it looks:
```yml
Layout/ArrayAlignment:
Description: >-
Align the elements of an array literal if they span more than
one line.
StyleGuide: '#align-multiline-arrays'
Enabled: true
VersionAdded: '0.49'
VersionChanged: '0.77'
```
So I decided to write …

[Fix #130] Layout/ArrayAlignment extended so now you can use with_fixed_indentation

---

README.md
config/base.yml
lib/datarockets/style/cop/layout/array_alignment_extended.rb
manual/cops_layout.md
spec/datarockets/style/cop/layout/array_alignment_extended_spec.rb

Here are fixes after Roma's review of [this PR](https://github.com/datarockets/datarockets-style/pull/151)
- Refactored base_column method of ArrayAlignmentExtended class in order to split it.
- Used variables in specs in order not to disable linter on them
- Removed comments in config because they are useless
- Created /manual folder in order to store docs there

Refactored Layout/ArrayAlignmentExtended

---

.rubocop.yml
CHANGELOG.md
config/base.yml
doc/STYLE_GUIDE.md
lib/datarockets/style.rb
lib/datarockets/style/cop/style/nested_interpolation.rb
manual/cops_layout.md
spec/datarockets/style/cop/style/nested_interpolation_spec.rb

Resolves issue #91 . Also, I'm going to send this cop to the rubocop repo. 

[#91] Add nested interpolation cop

---

CHANGELOG.md
Gemfile.lock
config/base.yml
datarockets-style.gemspec
doc/STYLE_GUIDE.md

Update Rubocop to 0.80

---

CHANGELOG.md
Gemfile.lock
config/base.yml
datarockets-style.gemspec

This PRs update rubocop to 0.88. Left all cops by default but changed only this cop https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem

Update rubocop version to 0.88

---

CHANGELOG.md

Reverts datarockets/datarockets-style#241
@paydaylight I'll revert this PR cause I'm absolutely diagredd this versions '1.0.1' the next reason:
1) We have rules about naming the releases https://github.com/datarockets/datarockets-style/blob/master/RELEASING.md . So you can see that any changes, which update dependencies, also changes minor version (not patch version) 
Also in this document, we have a check list which we're doing on release https://github.com/datarockets/datarockets-style/blob/master/RELEASING.md and some steps are missed
- Update version.rb file accordingly.
- ~Update CHANGELOG.md file.~
- Update Gemfile.lock file via running bundle install.
- Build and publish (and verify that everything ok):
- Tag the release: git tag vVERSION.
- ~Push changes: git push --tags.~
- …

Revert "fix release version in changelog"

---

CHANGELOG.md
Gemfile.lock
config/base.yml
doc/STYLE_GUIDE.md
lib/datarockets_style/version.rb
spec/datarockets_style/cop/layout/array_alignment_extended_spec.rb
spec/datarockets_style/formatter/todo_list_formatter/report_summary_spec.rb
spec/datarockets_style/formatter/todo_list_formatter_spec.rb

* Added `EnforcedStyleForMultiline: comma`  for `Style/TrailingCommaInArguments` and `Style/TrailingCommaInArrayLiteral`.
* Did not enable `Style/TrailingCommaInBlockArgs` because of safety warnings and unsure usage purpose

[Fix #233] Add more trailing comma rules

---

CHANGELOG.md
README.md

* Fixed `--require` cli flag to target new module path.
* Fixed `TodoListFormatter` output to match the new module path.
* Bumped gem's version.

[Fix #251] Update readme to match release changes

---

CHANGELOG.md
datarockets-style.gemspec

Bump rubocop to 1.10 in gemspec

[Fix #253] Bump rubocop to 1.10

---

CHANGELOG.md
datarockets-style.gemspec

Set rubocop-rails's version to a latest minor release (2.9)

[Fix #124] Specify strict version of rubocop-rails

---

CHANGELOG.md
config/base.yml
spec/rubocop_examples/hash_styles.rb

This PR fixes issue: https://github.com/datarockets/ruby-style/issues/179

(Fix #179) Fix alignment for lambdas and blocks
