datarockets/ruby-style

- RELEASING.md
This PR close #5 and adds actions which we should do for releasing
> [Fix #5] Add  releasing notes

- Gemfile.lock
- datarockets-style.gemspec
> [Fix #13] Update ruby vesrions

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
> [Fix #12] Fix and change md files

- README.md
> [Fix #10] Fix version badge

- CONTRIBUTING.md
> [Fix #44] Add additional note to contributing rules

- datarockets-style.gemspec
> [Fix #30] Add required ruby version

- CHANGELOG.md
- STYLE_GUIDE.md
- default.yml
> [Fix #29] Add rules for using rspec subjects

- CHANGELOG.md
- datarockets-style.gemspec
> [Fix #50] Update rubocop version to 0.73

- CHANGELOG.md
Adds a better description for an external fix
> [Fix #57] Add more info to the changelog

- .github/ISSUE_TEMPLATE/new-issue.md
- .github/ISSUE_TEMPLATE/update-dependencies.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR implements ideas which we discussed in the #48 issue
> [Fix #48] Add PR and issues templates

- CHANGELOG.md
- default.yml
> [Fix #65] Disable rubocop for node modules directory

- .github/ISSUE_TEMPLATE/new-issue.md
- .github/ISSUE_TEMPLATE/update-dependencies.md
- .github/PULL_REQUEST_TEMPLATE.md
>  Clean up issues and PR templates

- STYLE_GUIDE.md
This PR contains the ideas which we discussed on #39 issue. 
1) We leave aligning multi-line calls by fixed indentions. Main motivation:  https://github.com/datarockets/datarockets-style/issues/39#issuecomment-509710947
2) As a recommended approach, we prefer to write each argument on the separate line: https://github.com/datarockets/datarockets-style/issues/39#issuecomment-511474175
Before you submit a pull request, please make sure you have to follow: 
> [Fix #39] Add new comment bby aligning multi-line method calls

- STYLE_GUIDE.md
> [Fix #69] Fink the link for "Write empty methods in an expanded way"

- CHANGELOG.md
- Gemfile.lock
- datarockets-style.gemspec
> [Fix #61] Update rubocop-rspec version to 1.34.1

- CHANGELOG.md
- Gemfile.lock
- datarockets-style.gemspec
> [Fix #75] Update rubocop version to 0.74

- CHANGELOG.md
- Gemfile.lock
- datarockets-style.gemspec
> [Fix #81] Update RuboCop RSpec to 1.35.0

- CHANGELOG.md
- STYLE_GUIDE.md
- config/default.yml
> [Fix #85] use leading underscores in cached instance variable name

- CHANGELOG.md
- STYLE_GUIDE.md
- config/default.yml
Issue https://github.com/datarockets/datarockets-style/issues/84
> [Fix #84] Allow use 'for' with RSpec/ContextWording cop

- CHANGELOG.md
- STYLE_GUIDE.md
- config/default.yml
> [Fix #34] Fix 'Layout/MultilineMethodCallIndentation' for fixed indentation

- CHANGELOG.md
- STYLE_GUIDE.md
- config/default.yml
This PR resolves issue #33 and it fixes some indentation issues 
> [Fix #33] Fix indention for hash arguments

- README.md
- STYLE_GUIDE.md
This PR accumulate all thought from #40 issue that we don't need any restricted rule for string quoting  
> [Fix #40] Do not make any required rules for string literals quoting

- CHANGELOG.md
- config/rspec.yml
- doc/STYLE_GUIDE_RSPEC.md
> [Fix #94] Set up RSpec/MessageSpies cop

- .rubocop.yml
- Gemfile
- config/ruby.yml
- datarockets-style.gemspec
- lib/datarockets/style.rb
- lib/datarockets/style/version.rb
> Setup rubocop for datarockets-style

- CHANGELOG.md
- config/rspec.yml
- doc/STYLE_GUIDE_RSPEC.md
>  [Fix #114] Set up RSpec/ExampleLength cop

- CHANGELOG.md
- config/rspec.yml
- doc/STYLE_GUIDE_RSPEC.md
> [Fix #36] Disable RSpec/NestedGroups cop

- .rspec
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- datarockets-style.gemspec
- lib/datarockets/style.rb
- lib/datarockets/style/formatter/todo_list_formatter.rb
- lib/datarockets/style/formatter/todo_list_formatter/report_summary.rb
- spec/datarockets/style/formatter/todo_list_formatter/report_summary_spec.rb
- spec/datarockets/style/formatter/todo_list_formatter_spec.rb
- spec/datarockets/style/version_spec.rb
- spec/spec_helper.rb
That PR added formatter with todo list for cops for easier fixing a big number of offenses step-by-step 
See #107 
> [Fix #107] Add new formatter for todo list items

- CHANGELOG.md
- README.md
- lib/datarockets/style/formatter/todo_list_formatter/report_summary.rb
- spec/datarockets/style/formatter/todo_list_formatter/report_summary_spec.rb
- spec/datarockets/style/formatter/todo_list_formatter_spec.rb
> [Fix #124] Fix issue with todo list formatter result

- README.md
- doc/STYLE_GUIDE_RSPEC.md
> [Fix #117] Add notes about Rspec linting configuration

- doc/STYLE_GUIDE.md
> [Fix #131] Bug in documentation

- .github/PULL_REQUEST_TEMPLATE.md
> [Close #138] fix Contribution guide link in PR template

- .github/workflows/main.yml
- Makefile
> [Close #125] Setup Github Actions

- CHANGELOG.md
- README.md
- doc/STYLE_GUIDE.md
- doc/STYLE_GUIDE_RSPEC.md
Checked files:
- STYLE_GUIDE.md
- STYLE_GUIDE_RAILS.md
- STYLE_GUIDE_RSPEC.md
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Used this service for check - https://www.onlinecorrection.com/
Fix #146
> [Fix #146] Fixed typos and grammatical errors in all text files

- CHANGELOG.md
- config/rspec.yml
- doc/STYLE_GUIDE_RSPEC.md
> [#58] disable RSpec/LetSetup cop by default

- CHANGELOG.md
- Gemfile.lock
- config/rails.yml
- datarockets-style.gemspec
> [Close #155] setup rubocop-rails

- CHANGELOG.md
- config/rails.yml
- doc/STYLE_GUIDE_RAILS.md
Setup documentation for all cases except `app` directory in Rails config. Fix issue # 31
> [Fix #31] Setup Style/Documentation

- CHANGELOG.md
- Gemfile.lock
- datarockets-style.gemspec
> [Close #122] Update Rubocop-Rspec to 1.38.0

- CHANGELOG.md
- config/base.yml
- doc/STYLE_GUIDE_RAILS.md
> [Fix #19] Setup Style/ClassAndModuleChildren cop

- CHANGELOG.md
- README.md
- config/rspec.yml
> [Fix #58] Enable RSpec/LetSetup by default

- CHANGELOG.md
- Gemfile.lock
- config/base.yml
- lib/datarockets/style/formatter/todo_list_formatter/report_summary.rb
This PR justs updates rubocop to latest version.
> Update rubocop 0 81

- .rubocop.yml
- CHANGELOG.md
- Gemfile.lock
- datarockets-style.gemspec
This PR updates some dependencies and drop support for Ruby 2.3.
> [Close #183] Update dependencies and drop support for ruby 2.3

- .github/ISSUE_TEMPLATE/update-dependencies.md
- CHANGELOG.md
- config/base.yml
This PR adds pending cop to config 
> [Fix #180] Setup pending cops

- CHANGELOG.md
> Bump rubocop-rspec from 1.39.0 to 1.42.0 

- RELEASING.md
> [Fix #215] Add versioning stragety rules

- CHANGELOG.md
- config/base.yml
- doc/STYLE_GUIDE.md
- spec/datarockets/style/cop/layout/array_alignment_extended_spec.rb
> [Fix #218] Setup Style/TrailingCommaInHashLiteral cop

- CHANGELOG.md
Accidentally  specified ```1.0.1``` instead of ```1.1.0``` in changelog.
> fix release version in changelog

- CHANGELOG.md
- config/base.yml
Description: setting ```Layout/MultilineOperationIndentation``` to indented will follow [this](https://github.com/datarockets/datarockets-style/blob/master/doc/STYLE_GUIDE.md#style-parameters-aligning) style guide entry
> [Fix #177] set Layout/MultilineOperationIndentation to indented

- .rubocop.yml
- CHANGELOG.md
- README.md
- config/base.yml
- config/rails-locales.yml
- config/rails.yml
- datarockets-style.gemspec
- lib/datarockets_style/cop/layout/array_alignment_extended.rb
- lib/datarockets_style/cop/rspec/prefer_before_over_setup.rb
- spec/datarockets_style/formatter/todo_list_formatter_spec.rb
- spec/datarockets_style/version_spec.rb
Update dependencies
Fix issues:
https://github.com/datarockets/ruby-style/issues/262
https://github.com/datarockets/ruby-style/issues/260
https://github.com/datarockets/ruby-style/issues/261
> Update dependencies for version 1.3.0

- CHANGELOG.md
- Gemfile
- config/base.yml
- datarockets-style.gemspec
- lib/datarockets_style.rb
- lib/datarockets_style/cop/style/nested_interpolation.rb
- lib/datarockets_style/formatter/todo_list_formatter.rb
- lib/datarockets_style/formatter/todo_list_formatter/report_summary.rb
- lib/datarockets_style/version.rb
- spec/datarockets_style/cop/rspec/prefer_before_over_setup_spec.rb
- spec/datarockets_style/cop/style/nested_interpolation_spec.rb
- spec/datarockets_style/formatter/todo_list_formatter/report_summary_spec.rb
- spec/datarockets_style/formatter/todo_list_formatter_spec.rb
- spec/datarockets_style/version_spec.rb
- spec/spec_helper.rb
> Add Style/FrozenStringLiteralComment cop

- CHANGELOG.md
- lib/datarockets_style/cop/layout/array_alignment_extended.rb
- spec/datarockets_style/cop/layout/array_alignment_extended_spec.rb
- spec/rubocop_examples/cop/layout/array_alignment_extended_spec.rb
> (Fix #196) Fix Layout/ArrayAlignmentExtended cop

- CHANGELOG.md
- config/base.yml
- spec/rubocop_examples/hash_styles.rb
> (Fix #176) Fix hash alignment

- CHANGELOG.md
- config/base.yml
- spec/rubocop_examples/cop/layout/array_alignment_extended_spec.rb
> (Fix #258) Layout/ArrayAlignmentExtended works incorrectly

- CHANGELOG.md
- README.md
- config/graphql.yml
- datarockets-style.gemspec
- doc/STYLE_GUIDE_GRAPHQL.md
Added GraphQL cops from https://github.com/DmitryTsepelev/rubocop-graphql
> Add graphql cops
